# cotire.cmake 1.7.9 generated file
# /Users/admos/Documents/codesource/json/test/json_unit_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/Users/admos/Documents/codesource/json/cmake/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.7.9")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "3")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_FLAGS_NONE "-std=gnu++11")
set (COTIRE_TARGET_CONFIGURATION_TYPES "None")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "/Users/admos/Documents/codesource/json")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_NONE "/Users/admos/Documents/codesource/json/test/src;/Users/admos/Documents/codesource/json/test/thirdparty/catch;$<BUILD_INTERFACE:/Users/admos/Documents/codesource/json/src>;$<INSTALL_INTERFACE:include/nlohmann>")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "src/unit-algorithms.cpp;src/unit-allocator.cpp;src/unit-capacity.cpp;src/unit-cbor.cpp;src/unit-class_const_iterator.cpp;src/unit-class_iterator.cpp;src/unit-class_lexer.cpp;src/unit-class_parser.cpp;src/unit-comparison.cpp;src/unit-concepts.cpp;src/unit-constructor1.cpp;src/unit-constructor2.cpp;src/unit-convenience.cpp;src/unit-conversions.cpp;src/unit-deserialization.cpp;src/unit-element_access1.cpp;src/unit-element_access2.cpp;src/unit-inspection.cpp;src/unit-iterator_wrapper.cpp;src/unit-iterators1.cpp;src/unit-iterators2.cpp;src/unit-json_patch.cpp;src/unit-json_pointer.cpp;src/unit-meta.cpp;src/unit-modifiers.cpp;src/unit-msgpack.cpp;src/unit-noexcept.cpp;src/unit-pointer_access.cpp;src/unit-readme.cpp;src/unit-reference_access.cpp;src/unit-regression.cpp;src/unit-serialization.cpp;src/unit-testsuites.cpp;src/unit-udt.cpp;src/unit-unicode.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "")
set (CMAKE_CXX_COMPILER_ID "AppleClang")
set (CMAKE_CXX_COMPILER_VERSION "8.1.0.8020042")
set (CMAKE_CXX_COMPILER "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem")
set (CMAKE_CXX_FRAMEWORK_SEARCH_FLAG "-F")
set (CMAKE_CXX_SYSTEM_FRAMEWORK_SEARCH_FLAG "-iframework ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
